/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screens;

/**
 *
 * @author iragu
 */
public class MainMenu extends javax.swing.JFrame {
    
    /**
     * Creates new form DoublyLinkedList
     */
    public MainMenu() {
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnLinkedList = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        btnSimple = new javax.swing.JMenuItem();
        btnCircular = new javax.swing.JMenuItem();
        btnDoubly = new javax.swing.JMenuItem();
        btnStack = new javax.swing.JMenu();
        btnStackList = new javax.swing.JMenuItem();
        btnQueue1 = new javax.swing.JMenu();
        btnQueueList = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("MS PGothic", 0, 18)); // NOI18N
        jLabel1.setText("Experiencia Educativa:");

        jLabel2.setFont(new java.awt.Font("MS PGothic", 0, 36)); // NOI18N
        jLabel2.setText("Proyecto final");

        jLabel3.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        jLabel3.setText("Estructura de datos");

        jLabel4.setFont(new java.awt.Font("MS PGothic", 0, 18)); // NOI18N
        jLabel4.setText("Alumna:");

        jLabel5.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        jLabel5.setText("Iraís Aguirre Valente");

        btnLinkedList.setText("Lista");

        jMenu1.setText("Simple");

        btnSimple.setText("Lista simple");
        btnSimple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpleActionPerformed(evt);
            }
        });
        jMenu1.add(btnSimple);

        btnCircular.setText("Lista circular simple");
        btnCircular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCircularActionPerformed(evt);
            }
        });
        jMenu1.add(btnCircular);

        btnLinkedList.add(jMenu1);

        btnDoubly.setText("Doble");
        btnDoubly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoublyActionPerformed(evt);
            }
        });
        btnLinkedList.add(btnDoubly);

        jMenuBar1.add(btnLinkedList);

        btnStack.setText("Pila");
        btnStack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStackActionPerformed(evt);
            }
        });

        btnStackList.setText("Programa pila");
        btnStackList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStackListActionPerformed(evt);
            }
        });
        btnStack.add(btnStackList);

        jMenuBar1.add(btnStack);

        btnQueue1.setText("Cola");

        btnQueueList.setText("Programa cola");
        btnQueueList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQueueListActionPerformed(evt);
            }
        });
        btnQueue1.add(btnQueueList);

        jMenuBar1.add(btnQueue1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(180, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(172, 172, 172))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(248, 248, 248))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel2)
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCircularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCircularActionPerformed
        // TODO add your handling code here:
        
        AdministrativeCircular admin = new AdministrativeCircular();
        admin.setVisible(true);
        
    }//GEN-LAST:event_btnCircularActionPerformed

    private void btnSimpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpleActionPerformed
        // TODO add your handling code here:
        
        new StudentsSimpleList().setVisible(true);       
        
    }//GEN-LAST:event_btnSimpleActionPerformed

    private void btnDoublyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoublyActionPerformed
        // TODO add your handling code here:
        
        ProfessorDoublyList professor = new ProfessorDoublyList();
        professor.setVisible(true);
        
    }//GEN-LAST:event_btnDoublyActionPerformed

    private void btnQueueListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQueueListActionPerformed
        // TODO add your handling code here:
        
        QueueCinema queue = new QueueCinema();
        queue.setVisible(true);
        
    }//GEN-LAST:event_btnQueueListActionPerformed

    private void btnStackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStackActionPerformed

    private void btnStackListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStackListActionPerformed
        // TODO add your handling code here:
        
        StackBooks stack = new StackBooks();
        stack.setVisible(true);
        
    }//GEN-LAST:event_btnStackListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnCircular;
    private javax.swing.JMenuItem btnDoubly;
    private javax.swing.JMenu btnLinkedList;
    private javax.swing.JMenu btnQueue1;
    private javax.swing.JMenuItem btnQueueList;
    private javax.swing.JMenuItem btnSimple;
    private javax.swing.JMenu btnStack;
    private javax.swing.JMenuItem btnStackList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    // End of variables declaration//GEN-END:variables
}
